FROM node:9.11.2-slim
ENV PORT 8090

RUN apt-get update && apt-get -y install libpng-dev

WORKDIR /app

COPY .gitignore .
COPY internals internals/
COPY server server/
COPY yarn.lock .
COPY package.json .
RUN yarn install

COPY app app/
RUN yarn build

CMD ["yarn", "run", "start:prod"]
