FROM python:3.6-alpine

WORKDIR /app

RUN apk update && apk add gcc musl-dev linux-headers build-base
ENV PIP_SHIMS_BASE_MODULE=pipenv.patched.notpip
RUN pip install pipenv

COPY Pipfile .
RUN pipenv run pip install pip==18.0
RUN pipenv install --skip-lock

COPY manage.py .
COPY proxy proxy/
COPY terminator terminator/

CMD ["gunicorn", "terminator.wsgi:application", "--bind", "0.0.0.0:8091"]