FROM python:3.6-alpine

WORKDIR /app

RUN apk update && apk add gcc musl-dev

COPY requirements.txt .
COPY manage.py .
COPY proxy proxy/
COPY terminator terminator/

RUN pip install -r requirements.txt

CMD ["gunicorn", "terminator.wsgi:application", "--bind", "0.0.0.0:8000"]
