FROM python:3.6-alpine

WORKDIR /app

RUN apk update && apk add gcc musl-dev linux-headers build-base

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY manage.py .
COPY proxy proxy/
COPY terminator terminator/


CMD ["gunicorn", "terminator.wsgi:application", "--bind", "0.0.0.0:8091"]
