// +build !ignore_autogenerated

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Terminator) DeepCopyInto(out *Terminator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Terminator.
func (in *Terminator) DeepCopy() *Terminator {
	if in == nil {
		return nil
	}
	out := new(Terminator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Terminator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerminatorList) DeepCopyInto(out *TerminatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Terminator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerminatorList.
func (in *TerminatorList) DeepCopy() *TerminatorList {
	if in == nil {
		return nil
	}
	out := new(TerminatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TerminatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerminatorSpec) DeepCopyInto(out *TerminatorSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerminatorSpec.
func (in *TerminatorSpec) DeepCopy() *TerminatorSpec {
	if in == nil {
		return nil
	}
	out := new(TerminatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerminatorStatus) DeepCopyInto(out *TerminatorStatus) {
	*out = *in
	if in.MemcacheNode != nil {
		in, out := &in.MemcacheNode, &out.MemcacheNode
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RedisNode != nil {
		in, out := &in.RedisNode, &out.RedisNode
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerminatorStatus.
func (in *TerminatorStatus) DeepCopy() *TerminatorStatus {
	if in == nil {
		return nil
	}
	out := new(TerminatorStatus)
	in.DeepCopyInto(out)
	return out
}
